spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway?currentSchema=spendanalytic
    username: postgres
    password: JMArwowfFPLgfTTOXoeKpGxJBmcHmFtz
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: spendanalytic

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForJWT2024LongEnoughForHS256Algorithm}
    access: ${JWT_ACCESS:900000}
    refresh: ${JWT_REFRESH:86400000}
