spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?currentSchema=spendanalytic
    username: ${PGUSER}
    password: ${PGPASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: spendanalytic

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS:900000}
    refresh: ${JWT_REFRESH:86400000}
